import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Main.module.css'
import Card from '../components/Card'

export default function Home() {
  return (
    <>
    <div className={`${styles.container} ${styles.bg_vpale_blue}`}>
      <Head>
        <title>Order Summary Card</title>
        <meta name="description" content="Generated by Laveezah Noor" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <main className={styles.main}>
      <Card/>
      </main>
    </div>
    <footer className={styles.footer}>
      Challenge by <Link href="https://www.frontendmentor.io?ref=challenge" target="_blank">Frontend Mentor</Link>. 
      Coded by <a className={styles.name} href="https://www.linkedin.com/in/laveezah-noor/">Laveezah Noor</a>.
      </footer>
    </>
    )
}
